### ISSUE TITLE
Waveshaper

### ISSUE THREAD

**Issue by desafinadude** [mattlima/mooog#6]
Hi...
Firstly...amazing work! 

I have a question about using the waveshaper as a track node...
I tried this but it complains about tahn not being defined.

`{ id: "filter", node_type: "WaveShaper", curve: tahn(2) }`

**Comment by mattlima** [comment]
Hey! Thanks for the interest and the star; sorry this response took so long, I lost the notification in my inbox. I think your problem is a typo; the curve you're looking for is `tanh` not `tahn`.  Let me know if you have any other problems. I'm closing this for now.
